services:

  # ============================================================
  # POSTGRESQL DATABASE
  # ============================================================

  postgres:
    image: postgres:16
    container_name: streamops-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamops

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - streamops-network


  # ============================================================
  # STREAMOPS FASTAPI BACKEND
  # ============================================================

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: streamops-backend
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/streamops

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    volumes:
      - ./backend:/app

    networks:
      - streamops-network

    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"


  # ============================================================
  # PROMETHEUS
  # ============================================================

  prometheus:
    image: prom/prometheus:latest
    container_name: streamops-prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - backend

    networks:
      - streamops-network


  # ============================================================
  # GRAFANA
  # ============================================================

  grafana:
    image: grafana/grafana:latest
    container_name: streamops-grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

    networks:
      - streamops-network


# ==============================================================
# VOLUMES
# ==============================================================

volumes:

  postgres_data:

  prometheus_data:

  grafana_data:


# ==============================================================
# NETWORK
# ==============================================================

networks:

  streamops-network:
    driver: bridge
