apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamops

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - auth-service.yaml
  - catalog-service.yaml
  - playback-service.yaml
  - recommendation-service.yaml
  - notification-service.yaml
  - integrity-service.yaml
  - gateway.yaml
  - monitoring.yaml
  - autoscaling.yaml
  - pdb.yaml
  - self-healing.yaml

images:
  - name: streamops/auth-service
    newName: streamops/auth-service
    newTag: latest
  - name: streamops/catalog-service
    newName: streamops/catalog-service
    newTag: latest
  - name: streamops/playback-service
    newName: streamops/playback-service
    newTag: latest
  - name: streamops/recommendation-service
    newName: streamops/recommendation-service
    newTag: latest
  - name: streamops/notification-service
    newName: streamops/notification-service
    newTag: latest
  - name: streamops/integrity-service
    newName: streamops/integrity-service
    newTag: latest
  - name: streamops/gateway
    newName: streamops/gateway
    newTag: latest
