global:
  scrape_interval: 5s

rule_files:
  - "alert_rules.yml"

scrape_configs:

  - job_name: "gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "gateway:8000"

  - job_name: "auth-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-auth-service:8001"

  - job_name: "catalog-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-catalog-service:8002"

  - job_name: "playback-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-playback-service:8003"

  - job_name: "recommendation-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-recommendation-service:8004"

  - job_name: "notification-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-notification-service:8005"

  - job_name: "integrity-service"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "streamops-integrity-service:8006"